# Generated by Django 3.0 on 2022-03-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='content_media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField()),
                ('name', models.CharField(max_length=40)),
                ('size', models.CharField(max_length=15)),
                ('path', models.CharField(max_length=200)),
            ],
        ),
    ]
