# Generated by Django 3.0 on 2022-03-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainbody', '0002_task_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='content_media',
            name='duration',
            field=models.CharField(default='00:00:00:00', max_length=12),
        ),
    ]
